# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Pure Blog
email: santone.kassim@gmail.com
description: Hello world. Welcome to the pure blog for all things "pure".
baseurl: "thepureblog"
url: "https://www.thepureblog.com"

github_path: https://www.github.com/ksantone
linkedin_path: http://www.linkedin.com/in/ksantone

pathToBlogImgBin: /assets/img/blog/

# Build settings
permalink: pretty
gems:
  - jekyll-feed
  - jekyll-autoprefixer
sass:
  sass_dir: _sass